server:
  port: 8081
spring:
    thymeleaf:
      cache: false
      mode: HTML
      encoding: UTF-8
      servlet:
        content-type: text/html
  #      prefix: classpath:/templates

    datasource:
      url: jdbc:mysql://localhost:3306/xkjs?serverTimezone=UTC&username&password&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
    servlet:
      multipart:
        enabled: true
        max-file-size: 50MB
        max-request-size: 50MB

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.team5101.pojo
